kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: managed-disk-hdd-1g
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

