kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azure-file-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-file
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

